#!/bin/bash

MW2_LOG_LEVEL=debug MW2_LOG_SENSITIVE=true MW2_CAPTURE_ENABLED=true MW2_MATCHMAKING_PREFER_EARLIER_HOSTS=true MW2_BANDWIDTH_SEND_DURATION_MS=50 MW2_BANDWIDTH_FINALIZE_RECEIVE_PERIOD_MS=40 go run ./cmd/mw2-server/main.go 2>&1 | tee server_log.log


