log-queries

# Forward unhndled requests to a public DNS server
server=1.1.1.1
server=1.0.0.1

# Do not use host /etc/hosts file
no-hosts

# Custom Demonware DNS Redirects for MW2 PS3
address=/mw2-ps3-auth.mmp3.demonware.net/192.168.0.207
address=/mw2-ps3-lsg.live.mmp3.demonware.net/192.168.0.207