bind-interfaces
listen-address=0.0.0.0
port=53

server=1.1.1.1
server=1.0.0.1
no-resolv
no-hosts
log-queries

address=/mw2-ps3-auth.mmp3.demonware.net/__MW2_DNS_REDIRECT_IP__
address=/mw2-ps3-lsg.live.mmp3.demonware.net/__MW2_DNS_REDIRECT_IP__
address=/web1.ps3.iw4.iwnet.infinityward.com/__MW2_DNS_REDIRECT_IP__
